### PR TITLE
Fixed StrategyInterface::hydrate() docblock because it is not optional

### PR DESCRIPTION
**Pull request by svycka**
|    Q          |   A
|-------------- | ------
| Documentation | yes

### CODE REVIEW

**Comment by froschdesign** [comment]
A bigger problem is included in the documentation: https://docs.laminas.dev/laminas-hydrator/v3/strategy/#introduction

**Comment by svycka** [comment]
whops wrong branch bet I see documentation issue so will leave as it is as I don't know how you will address this good luck

**Review by settermjd — APPROVED** [review]
Looks good. Thanks for making the change, @svycka. One final step required, https://github.com/laminas/laminas-hydrator/pull/23/checks?check_run_id=1003015316.

**Comment by svycka** [comment]
@settermjd I have fixed it. But I think this is not a docblock bug but interface should allow optional context. I think @weierophinney introduced this unintentionally when added typehints. Also as @froschdesign noted documentation has it correctly https://docs.laminas.dev/laminas-hydrator/v3/strategy/#introduction but changing interface now I am not sure it's BC break or not?

@weierophinney what do you think?

**Comment by froschdesign** [comment]
The title of this pull request is to the update the DocBlock and this must be done in the related PHP file and documentation file.

Everything else needs a new issue report or a discussion in the [forum](https://discourse.laminas.dev).

**Pull request merged**
