### PR TITLE
Allow null for Boolean and Collection strategies.

### PR DESCRIPTION
**Pull request by xorock**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description

All strategies except of Boolean and CollectionStrategy allows to hydrate/extract null values. This fix adds support for null values which makes all strategies more consistent, and adds language nullable type compatibility.

### CODE REVIEW

**Comment by rieschl** [comment]
Hmm, isn't that a bc break?

**Comment by froschdesign** [comment]
@rieschl 
> Hmm, isn't that a bc break?

Correct, because existing tests are modified, which indicates a different behaviour.
And also with the new tests: without the implementation in the concrete classes they will fail.

**Comment by froschdesign** [comment]
@xorock 
In the forum I gave you a solution / workaround:

```php
$hydrator = new Laminas\Hydrator\ReflectionHydrator();
$hydrator->addStrategy(
    'tracks',
    new Laminas\Hydrator\Strategy\StrategyChain(
        [
            new Laminas\Hydrator\Strategy\CollectionStrategy(
                new Laminas\Hydrator\ReflectionHydrator(),
                Track::class
            ),
            new Laminas\Hydrator\Strategy\ClosureStrategy(
                null,
                static function ($value) {
                    return $value ?? [];
                }
            ),
        ]
    )
);
```

And you have suggested another solution without changing the existing behaviour.

Otherwise we have to wait for a new major version.

https://discourse.laminas.dev/t/hydrator-nullable-collection-strategy/1932/2?u=froschdesign

**Comment by xorock** [comment]
Yes, but Your solution only changes value to array, still null is not allowed and thus cannot be used properly with nullable properties.

**Comment by froschdesign** [comment]
@xorock 
> Yes, but Your solution only changes value to array, still null is not allowed and thus cannot be used properly with nullable properties.

Not that misunderstandings arise: It's a workaround, correct. But also a starting point to develop a new strategy.

**Comment by weierophinney** [comment]
Closing in favor of #43.

**Pull request closed without merging**
