### PR TITLE
Adds documentation for Collection strategy

### PR DESCRIPTION
**Pull request by froschdesign**
|    Q          |   A
|-------------- | ------
| Documentation | yes
| Enhancement        | yes

### CODE REVIEW

**Comment by michalbundyra** [comment]
Thanks, @froschdesign!

**Comment by froschdesign** [comment]
@michalbundyra 
Thanks but unfortunately the workflow for the docs build [failed](https://github.com/laminas/laminas-hydrator/actions/runs/173611517).

**Comment by froschdesign** [comment]
Problem here on GitHub: https://www.githubstatus.com/incidents/vm2xh5qb0nbk

**Comment by michalbundyra** [comment]
@froschdesign yup, reported to GitHub, so once it's solved I'll trigger the build again. Thanks!

**Pull request merged**
