### PR TITLE
Update psalm & baseline

### PR DESCRIPTION
**Pull request by sasezaki**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | yes

### Description
Updated 4.10.0 to 4.20.0, it will provide more good analysis.

#### Updated packages.

$ composer diff origin/4.4.x
| Prod Packages          | Operation | Base    | Target  |
|------------------------|-----------|---------|---------|
| symfony/polyfill-ctype | Upgraded  | v1.23.0 | v1.24.0 |

| Dev Packages                         | Operation | Base      | Target    |
|--------------------------------------|-----------|-----------|-----------|
| amphp/amp                            | Upgraded  | v2.6.0    | v2.6.1    |
| composer/package-versions-deprecated | Upgraded  | 1.11.99.3 | 1.11.99.5 |
| composer/pcre                        | New       | -         | 1.0.1     |
| composer/semver                      | Upgraded  | 3.2.5     | 3.2.9     |
| composer/xdebug-handler              | Upgraded  | 2.0.2     | 3.0.1     |
| nikic/php-parser                     | Upgraded  | v4.12.0   | v4.13.2   |
| phpdocumentor/reflection-docblock    | Upgraded  | 5.2.2     | 5.3.0     |
| phpdocumentor/type-resolver          | Upgraded  | 1.4.0     | 1.6.0     |
| symfony/console                      | Upgraded  | v5.3.7    | v5.4.3    |
| symfony/deprecation-contracts        | Upgraded  | v2.4.0    | v2.5.0    |
| symfony/polyfill-intl-grapheme       | Upgraded  | v1.23.1   | v1.24.0   |
| symfony/polyfill-intl-normalizer     | Upgraded  | v1.23.0   | v1.24.0   |
| symfony/polyfill-mbstring            | Upgraded  | v1.23.1   | v1.24.0   |
| symfony/polyfill-php73               | Upgraded  | v1.23.0   | v1.24.0   |
| symfony/polyfill-php80               | Upgraded  | v1.23.1   | v1.24.0   |
| symfony/service-contracts            | Upgraded  | v2.4.0    | v2.5.0    |
| symfony/string                       | Upgraded  | v5.3.7    | v5.4.3    |
| vimeo/psalm                          | Upgraded  | 4.10.0    | 4.20.0    |

### CODE REVIEW

**Comment by sasezaki** [comment]
My update operation seems wrong, composer install fails.
https://github.com/laminas/laminas-hydrator/runs/5156925604?check_suite_focus=true
So I changed to draft.

**Comment by Ocramius** [comment]
IMO drop PHP 7.3?

**Comment by sasezaki** [comment]
> My update operation seems wrong, composer install fails.
https://github.com/laminas/laminas-hydrator/runs/5156925604?check_suite_focus=true
So I changed to draft.

I did update again with PHP 7.3.
```
php7.3 $(which composer) require --dev vimeo/psalm:^4.20 -W
```

Ready for review now.

**Comment by Ocramius** [comment]
@sasezaki since the baseline has been adjusted, and you refactored the tests for the hydrator, could you please rebase this with a re-generated baseline? I'm fairly sure the tests will fail, with the baseline as-is and the new code fixes: not because of a bug, but just because of shifted code locations no longer covered by previous baseline.

**Comment by sasezaki** [comment]
@Ocramius 

> could you please rebase this with a re-generated baseline?

Done.

**Review by Ocramius — APPROVED** [review]
Thank you!

**Pull request merged**
